name: Deploy to Azure VM

on:
  workflow_dispatch:
  push:
    branches:
      - master  # Trigger on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          # Navigate to project directory
          cd /home/azureuser/stage6

          # Pull latest code
          git pull origin master

          # Ensure virtual environment exists and is updated
          if [ ! -d "env" ]; then
            python3 -m venv env
          fi
          source env/bin/activate
          pip install -r requirements.txt

          # Run deployment script
          ./deploy.sh